export const PHASE1_SCHEMA = {
  name: 'phase1_metadata',
  strict: true,
  schema: {
    type: 'object' as const,
    properties: {
      title: { type: 'string', description: 'Exact paper title as written' },
      authors: { type: 'array', items: { type: 'string' }, description: 'Full author names' },
      doi: { type: ['string', 'null'], description: 'DOI in format 10.xxxx/xxxxx without https://doi.org/ prefix' },
      abstract: { type: 'string', description: 'Complete abstract text' },
      journal: { type: 'string', description: 'Journal or conference name' },
      year: { type: 'integer', description: 'Publication year' },
      keywords: { type: 'array', items: { type: 'string' }, description: 'Paper keywords, empty array if none' },
      study_type: {
        type: 'string',
        enum: ['RCT', 'Cohort', 'Case-Control', 'Cross-Sectional', 'Systematic Review', 'Meta-Analysis', 'Narrative Review', 'Case Report', 'Methodology', 'Perspective', 'Editorial', 'Letter', 'Other'],
      },
      has_tables: { type: 'boolean', description: 'True if paper contains data tables' },
      has_figures: { type: 'boolean', description: 'True if paper contains figures/images' },
      estimated_pages: { type: 'integer', description: 'Estimated page count' },
      funding_sources: { type: ['string', 'null'], description: 'Funding sources if mentioned, null if not found' },
      conflict_of_interest: { type: ['string', 'null'], description: 'Conflict of interest statement, null if not found' },
      registration_number: { type: ['string', 'null'], description: 'Trial registration number (PROSPERO, ClinicalTrials.gov, etc.), null if not found' },
    },
    required: ['title', 'authors', 'doi', 'abstract', 'journal', 'year', 'keywords', 'study_type', 'has_tables', 'has_figures', 'estimated_pages', 'funding_sources', 'conflict_of_interest', 'registration_number'],
    additionalProperties: false,
  },
};

export const PHASE3_SCHEMA = {
  name: 'phase3_consensus',
  strict: true,
  schema: {
    type: 'object' as const,
    properties: {
      title: { type: 'string' },
      authors: { type: 'array', items: { type: 'string' } },
      doi: { type: ['string', 'null'] },
      pmid: { type: ['string', 'null'] },
      abstract: { type: 'string' },
      journal: { type: 'string' },
      year: { type: 'integer' },
      keywords: { type: 'array', items: { type: 'string' } },
      citations_count: { type: ['integer', 'null'] },
      publisher: { type: ['string', 'null'] },
      open_access: { type: ['boolean', 'null'] },
      orcid_ids: { type: 'array', items: { type: 'string' } },
      study_type: { type: ['string', 'null'] },
      funding_sources: { type: ['string', 'null'] },
      conflict_of_interest: { type: ['string', 'null'] },
      registration_number: { type: ['string', 'null'] },
      field_sources: {
        type: 'object',
        description: 'Provenance: which sources confirmed each field. Use | for confirmation, + for complement',
        additionalProperties: { type: 'string' },
      },
      conflicts_resolved: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            field: { type: 'string' },
            chosen: { type: 'string', description: 'The value chosen as correct, as a string' },
            reason: { type: 'string' },
          },
          required: ['field', 'chosen', 'reason'],
          additionalProperties: false,
        },
      },
      rejected_sources: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            source: { type: 'string' },
            reason: { type: 'string' },
          },
          required: ['source', 'reason'],
          additionalProperties: false,
        },
      },
    },
    required: ['title', 'authors', 'doi', 'pmid', 'abstract', 'journal', 'year', 'keywords', 'citations_count', 'publisher', 'open_access', 'orcid_ids', 'study_type', 'funding_sources', 'conflict_of_interest', 'registration_number', 'field_sources', 'conflicts_resolved', 'rejected_sources'],
    additionalProperties: false,
  },
};

export const PHASE4_SCHEMA = {
  name: 'phase4_extraction',
  strict: true,
  schema: {
    type: 'object' as const,
    properties: {
      methodology: { type: 'string', description: 'Detailed study design, architecture, or theoretical framework' },
      sample_size: { type: 'string', description: 'Sample size, dataset size, or scope. Cite page/table where found.' },
      population: { type: 'string', description: 'Population, dataset, or subjects studied' },
      intervention: { type: 'string', description: 'Core intervention, model, or phenomenon tested. Write "Not applicable" with reason if none.' },
      control: { type: 'string', description: 'Comparison group or baseline. Write "Not applicable" with reason if none.' },
      primary_outcomes: { type: 'string', description: 'Main results with specific numbers, p-values, CIs. Cite source (e.g. Table 1, p.5)' },
      secondary_outcomes: { type: 'string', description: 'Additional findings or secondary analyses' },
      main_results: { type: 'string', description: 'Synthesis of key results. What worked vs baseline?' },
      limitations: { type: 'string', description: 'Limitations acknowledged by the authors' },
      conclusions: { type: 'string', description: 'Final conclusions and implications' },
      ethical_considerations: { type: 'string', description: 'Ethics approval, data privacy, bias, conflicts of interest' },
      structured_outcomes: {
        type: 'array',
        description: 'Each quantitative outcome as a structured object for meta-analysis. One row per outcome per comparison.',
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', description: 'Short outcome name. For multi-group studies include comparison, e.g. "Task Time (Experts vs Novices)"' },
            comparison_type: { type: 'string', enum: ['single_arm', 'pairwise', 'network'], description: 'single_arm: one group only. pairwise: two groups compared. network: pairwise comparison that is part of a multi-treatment network.' },
            category: { type: 'string', enum: ['primary', 'secondary', 'exploratory', 'safety'] },
            type: { type: 'string', enum: ['continuous', 'binary', 'time_to_event', 'count', 'correlation', 'other'] },
            timepoint: { type: 'string', description: 'When measured, e.g. "6 months", "post-intervention". Use "cross-sectional" or "N/A" if not applicable' },
            arm1_label: { type: 'string', description: 'Exact name of first/main group from the paper (e.g. "AI Feedback", "Experts", "Treatment A")' },
            arm1_n: { type: ['integer', 'null'], description: 'Sample size for arm 1' },
            arm1_mean: { type: ['number', 'null'], description: 'Mean for arm 1 (continuous outcomes)' },
            arm1_sd: { type: ['number', 'null'], description: 'Standard deviation for arm 1' },
            arm1_events: { type: ['integer', 'null'], description: 'Number of events for arm 1 (binary outcomes)' },
            arm1_total: { type: ['integer', 'null'], description: 'Total participants for arm 1 (binary outcomes)' },
            arm2_label: { type: ['string', 'null'], description: 'Exact name of second/comparison group. Null for single_arm' },
            arm2_n: { type: ['integer', 'null'], description: 'Sample size for arm 2' },
            arm2_mean: { type: ['number', 'null'], description: 'Mean for arm 2 (continuous outcomes)' },
            arm2_sd: { type: ['number', 'null'], description: 'Standard deviation for arm 2' },
            arm2_events: { type: ['integer', 'null'], description: 'Number of events for arm 2 (binary outcomes)' },
            arm2_total: { type: ['integer', 'null'], description: 'Total participants for arm 2 (binary outcomes)' },
            proportion: { type: ['number', 'null'], description: 'For single_arm binary: the proportion (e.g. 0.73). Null otherwise.' },
            se_reported: { type: 'boolean', description: 'True if the paper reported SE instead of SD (SD was converted)' },
            correlation_pre_post: { type: ['number', 'null'], description: 'Pre-post correlation for paired/crossover designs. Null if not reported or not applicable' },
            effect_measure: { type: 'string', description: 'MD, SMD, WMD, OR, RR, RD, NNT, HR, incidence_rate, prevalence, IRR, AUC, sensitivity, specificity, PPV, NPV, LR+, r, R2, proportion, mean, other, N/A' },
            effect_size: { type: ['number', 'null'], description: 'Reported effect size value' },
            ci_lower: { type: ['number', 'null'], description: 'Lower bound of 95% CI' },
            ci_upper: { type: ['number', 'null'], description: 'Upper bound of 95% CI' },
            p_value: { type: ['string', 'null'], description: 'p-value as string, e.g. "0.003", "<0.001", "NS"' },
            direction_favorable: { type: 'string', enum: ['higher', 'lower', 'neutral'], description: 'Does a higher or lower value indicate a better outcome?' },
            source: { type: 'string', description: 'Where found: "Table 2", "Figure 3", "Results p.6". Use "Not specified" if unknown' },
          },
          required: ['name', 'comparison_type', 'category', 'type', 'timepoint', 'arm1_label', 'arm1_n', 'arm1_mean', 'arm1_sd', 'arm1_events', 'arm1_total', 'arm2_label', 'arm2_n', 'arm2_mean', 'arm2_sd', 'arm2_events', 'arm2_total', 'proportion', 'se_reported', 'correlation_pre_post', 'effect_measure', 'effect_size', 'ci_lower', 'ci_upper', 'p_value', 'direction_favorable', 'source'],
          additionalProperties: false,
        },
      },
    },
    required: ['methodology', 'sample_size', 'population', 'intervention', 'control', 'primary_outcomes', 'secondary_outcomes', 'main_results', 'limitations', 'conclusions', 'ethical_considerations', 'structured_outcomes'],
    additionalProperties: false,
  },
};

export const PHASE5_SCHEMA = {
  name: 'phase5_visual',
  strict: true,
  schema: {
    type: 'object' as const,
    properties: {
      figures: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string', description: 'e.g. Figure 1' },
            page: { type: 'integer', description: 'Page number where the figure appears' },
            caption: { type: 'string' },
            type: { type: 'string', description: 'graph, diagram, photo, flowchart, etc.' },
            content_description: { type: 'string', description: 'Detailed description combining visual trends with specific data points and values' },
          },
          required: ['id', 'page', 'caption', 'type', 'content_description'],
          additionalProperties: false,
        },
      },
      tables: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string', description: 'e.g. Table 1' },
            page: { type: 'integer', description: 'Page number where the table appears' },
            caption: { type: 'string' },
            content_summary: { type: 'string', description: 'Comprehensive summary with specific numbers, percentages, p-values tied to column headers' },
          },
          required: ['id', 'page', 'caption', 'content_summary'],
          additionalProperties: false,
        },
      },
      visual_summary: { type: 'string', description: 'How the visual evidence supports the papers main claims' },
    },
    required: ['figures', 'tables', 'visual_summary'],
    additionalProperties: false,
  },
};

export const PHASE6_SCHEMA = {
  name: 'phase6_consolidation',
  strict: true,
  schema: {
    type: 'object' as const,
    properties: {
      methodology: { type: 'string' },
      sample_size: { type: 'string' },
      population: { type: 'string' },
      intervention: { type: 'string' },
      control: { type: 'string' },
      primary_outcomes: { type: 'string' },
      secondary_outcomes: { type: 'string' },
      main_results: { type: 'string' },
      limitations: { type: 'string' },
      conclusions: { type: 'string' },
      ethical_considerations: { type: 'string' },
      consolidation_notes: { type: 'string', description: 'Major conflicts resolved, which models agreed/disagreed' },
      field_agreement: {
        type: 'array',
        description: 'Agreement summary for each scientific field. MUST contain exactly 11 entries, one for each field.',
        items: {
          type: 'object',
          properties: {
            field: { type: 'string', description: 'Field name: methodology, sample_size, population, intervention, control, primary_outcomes, secondary_outcomes, main_results, limitations, conclusions, or ethical_considerations' },
            agreement: { type: 'string', description: 'Agreement summary, e.g. "Full agreement (5/5)" or "4/5 agree on N=20, 1/5 reports N=22"' },
          },
          required: ['field', 'agreement'],
          additionalProperties: false,
        },
      },
      structured_outcomes: {
        type: 'array',
        description: 'Consolidated structured outcomes for meta-analysis, merged from all models. Use majority consensus for values; trust table/figure data over text.',
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', description: 'Outcome name with group comparison for multi-group studies, e.g. "Task Time (Experts vs Novices)"' },
            comparison_type: { type: 'string', enum: ['single_arm', 'pairwise', 'network'] },
            category: { type: 'string', enum: ['primary', 'secondary', 'exploratory', 'safety'] },
            type: { type: 'string', enum: ['continuous', 'binary', 'time_to_event', 'count', 'correlation', 'other'] },
            timepoint: { type: 'string' },
            arm1_label: { type: 'string' },
            arm1_n: { type: ['integer', 'null'] },
            arm1_mean: { type: ['number', 'null'] },
            arm1_sd: { type: ['number', 'null'] },
            arm1_events: { type: ['integer', 'null'] },
            arm1_total: { type: ['integer', 'null'] },
            arm2_label: { type: ['string', 'null'] },
            arm2_n: { type: ['integer', 'null'] },
            arm2_mean: { type: ['number', 'null'] },
            arm2_sd: { type: ['number', 'null'] },
            arm2_events: { type: ['integer', 'null'] },
            arm2_total: { type: ['integer', 'null'] },
            proportion: { type: ['number', 'null'] },
            se_reported: { type: 'boolean' },
            correlation_pre_post: { type: ['number', 'null'] },
            effect_measure: { type: 'string' },
            effect_size: { type: ['number', 'null'] },
            ci_lower: { type: ['number', 'null'] },
            ci_upper: { type: ['number', 'null'] },
            p_value: { type: ['string', 'null'] },
            direction_favorable: { type: 'string', enum: ['higher', 'lower', 'neutral'] },
            source: { type: 'string' },
            models_reporting: { type: 'integer', description: 'How many models reported this outcome' },
            agreement_note: { type: 'string', description: 'Note on agreement, e.g. "5/5 agree on Dice=0.442"' },
          },
          required: ['name', 'comparison_type', 'category', 'type', 'timepoint', 'arm1_label', 'arm1_n', 'arm1_mean', 'arm1_sd', 'arm1_events', 'arm1_total', 'arm2_label', 'arm2_n', 'arm2_mean', 'arm2_sd', 'arm2_events', 'arm2_total', 'proportion', 'se_reported', 'correlation_pre_post', 'effect_measure', 'effect_size', 'ci_lower', 'ci_upper', 'p_value', 'direction_favorable', 'source', 'models_reporting', 'agreement_note'],
          additionalProperties: false,
        },
      },
    },
    required: ['methodology', 'sample_size', 'population', 'intervention', 'control', 'primary_outcomes', 'secondary_outcomes', 'main_results', 'limitations', 'conclusions', 'ethical_considerations', 'consolidation_notes', 'field_agreement', 'structured_outcomes'],
    additionalProperties: false,
  },
};
